name: easy_onboard
description: A new Flutter Onboarding package. Easy to use and colourful design for your project.
version: 1.0.1
homepage: https://github.com/tyypgzl/easy_onboard


environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:

